#!/usr/bin/env bash
# Install nginx web server

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Allow HTTP and HTTPS traffic
sudo ufw allow 'Nginx HTTP'

# Start nginx
sudo service nginx start
echo "Hello World!" >/var/www/html/index.html

# Check if nginx is running
sudo service nginx status
