#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
backend web-backend
        balance roundrobin
        server 485447-web-01 18.209.223.50:80 check
        server 485447-web-02 34.207.154.139:80 check

frontend web-frontend_http
        bind *:80
        mode http
        default_backend web-backend" >>/etc/haproxy/haproxy.cfg

sudo service haproxy restart
