#!/usr/bin/env bash
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts /tmp/hosts
echo "127.0.0.2           localhost" >/tmp/hosts
echo "8.8.8.8           facebook.com" >>/tmp/hosts
cp -f /tmp/hosts /etc/hosts
